import { Project } from '../types';
import JSZip from 'jszip';

// VAPID public key would be generated by the backend in a real application
const VAPID_PUBLIC_KEY = 'BEl18-mYl5cSAj-pM8-2Gkl-k-b3-Jz-d_Y3jN8aU9bC2hY0k4bV-cM6jX9Z8Z3jX5f2aB6dC4gJ1eR7hH0wK9s';

const urlBase64ToUint8Array = (base64String: string) => {
  const padding = '='.repeat((4 - base64String.length % 4) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
};

export const subscribeUserToPush = async (): Promise<NotificationPermission> => {
    if (!('serviceWorker' in navigator) || !('PushManager' in window)) {
        alert('Push notifications are not supported by your browser.');
        return 'denied';
    }
    try {
        const registration = await navigator.serviceWorker.ready;
        let permission = Notification.permission;
        
        if (permission === 'default') {
            permission = await Notification.requestPermission();
        }

        if (permission === 'granted') {
            const subscription = await registration.pushManager.subscribe({
                userVisibleOnly: true,
                applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY)
            });
            console.log('Push subscription successful:', JSON.stringify(subscription));
            // In a real app, you would send this subscription object to your backend server.
        }
        
        return permission;
    } catch (error) {
        console.error('Failed to subscribe to push notifications:', error);
        return 'denied';
    }
};

export const showLocalNotification = async (title: string, options: NotificationOptions) => {
    if (!('serviceWorker' in navigator)) {
        return; // Notifications not supported
    }
    try {
        const registration = await navigator.serviceWorker.ready;
        if (Notification.permission === 'granted') {
            await registration.showNotification(title, options);
        }
    } catch (error) {
        console.error('Error showing local notification:', error);
    }
};


export const downloadProjectAsZip = async (project: Project) => {
    const zip = new JSZip();
    
    project.files.forEach(file => {
      zip.file(file.path, file.content);
    });

    if (project.previewFile) {
        // To avoid conflicts, name it uniquely if a file with the same path exists
        const finalPath = project.files.some(f => f.path === project.previewFile!.path) 
            ? `preview-${project.previewFile.path}` 
            : project.previewFile.path;
        zip.file(finalPath, project.previewFile.content);
    }

    if (project.appIcon) {
        const base64Data = project.appIcon.split(';base64,').pop();
        if (base64Data) {
            // These paths must match what the AI is told to use in manifest.json
            zip.file('icon-192x192.png', base64Data, { base64: true });
            zip.file('icon-512x512.png', base64Data, { base64: true });
        }
    }

    try {
      const content = await zip.generateAsync({ type: 'blob' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(content);
      const sanitizedName = project.name.replace(/[^a-z0-9]/gi, '_').toLowerCase();
      link.download = `${sanitizedName}.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(link.href);
    } catch (error) {
        console.error("Failed to generate zip file", error);
        alert("Sorry, there was an error downloading the project.");
    }
};

export const timeAgo = (dateString: string): string => {
  const date = new Date(dateString);
  const seconds = Math.floor((new Date().getTime() - date.getTime()) / 1000);
  let interval = seconds / 31536000;
  if (interval > 1) return Math.floor(interval) + " years ago";
  interval = seconds / 2592000;
  if (interval > 1) return Math.floor(interval) + " months ago";
  interval = seconds / 86400;
  if (interval > 1) return Math.floor(interval) + " days ago";
  interval = seconds / 3600;
  if (interval > 1) return Math.floor(interval) + " hours ago";
  interval = seconds / 60;
  if (interval > 1) return Math.floor(interval) + " minutes ago";
  if (seconds < 10) return "just now";
  return Math.floor(seconds) + " seconds ago";
};
