import React from 'react';

export const TermsPage: React.FC = () => {
  return (
    <div className="bg-white text-gray-800 min-h-screen font-sans">
      <header className="bg-white/80 backdrop-blur-lg z-20 border-b border-gray-200 sticky top-0">
        <nav className="container mx-auto px-6 py-3 flex justify-between items-center">
          <a href="#/" className="text-xl font-bold">Silo Build</a>
          <a href="#/" className="bg-blue-600 text-white px-4 py-2 text-sm rounded-full font-semibold hover:bg-blue-700 transition-colors">
            Back to Home
          </a>
        </nav>
      </header>
      <main className="container mx-auto px-6 py-12 max-w-4xl">
        <h1 className="text-4xl font-bold mb-6">Terms of Service</h1>
        <div className="prose prose-lg text-gray-700 space-y-4">
            <p>Last updated: {new Date().toLocaleDateString()}</p>
            <p>Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the Silo Build application (the "Service") operated by us.</p>
            <p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.</p>
            
            <h2 className="text-2xl font-semibold text-gray-900 pt-4">1. Accounts</h2>
            <p>When you create an account with us, you must provide us with information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.</p>
            
            <h2 className="text-2xl font-semibold text-gray-900 pt-4">2. Generated Content</h2>
            <p>Our Service allows you to generate code, text, and other materials ("Content"). You are responsible for the Content that you generate, including its legality, reliability, and appropriateness. You retain any and all of your rights to any Content you submit, post or display on or through the Service and you are responsible for protecting those rights.</p>
            <p>We do not claim ownership of the code you generate. You are free to use it for personal or commercial projects, subject to the licenses of any third-party libraries or assets that may be included.</p>

            <h2 className="text-2xl font-semibold text-gray-900 pt-4">3. Prohibited Uses</h2>
            <p>You may not use the Service for any illegal or unauthorized purpose. You agree to comply with all laws, rules, and regulations applicable to your use of the Service.</p>

            <h2 className="text-2xl font-semibold text-gray-900 pt-4">4. Termination</h2>
            <p>We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
            
            <h2 className="text-2xl font-semibold text-gray-900 pt-4">5. Disclaimer</h2>
            <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied. The code and information generated by the AI are for informational and development purposes only and are not guaranteed to be accurate, complete, or suitable for any particular purpose.</p>
            
            <h2 className="text-2xl font-semibold text-gray-900 pt-4">6. Changes to Terms</h2>
            <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will try to provide at least 30 days' notice prior to any new terms taking effect.</p>
            
            <h2 className="text-2xl font-semibold text-gray-900 pt-4">Contact Us</h2>
            <p>If you have any questions about these Terms, please contact us.</p>
            <p className="pt-6 font-bold text-red-600">Disclaimer: This is a template Terms of Service. You should consult with a legal professional to ensure it meets your specific needs.</p>
        </div>
      </main>
    </div>
  );
};